volumes:
  db:
services:
  importer:
    container_name: importer
    image: importer:1.0.0
    stop_grace_period: 30s
    depends_on:
      correios:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET}
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./:/app:z
    restart: unless-stopped
    extra_hosts:
      - "gazintech.dev:172.17.0.1"
  correios:
    container_name: correios
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
